name: MGWarlockTactical
main: com.comze_instancelabs.mgwarlocktactical.Main
version: 1.1.0
author: [InstanceLabs,mepeisen]
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   wlt:
      description: Main command
      usage: /wlt [action]
      aliases: [warlocktactical, mgwarlocktactical]
